#### 목차
- [Go 에러 처리의 기본 원칙](#go-에러-처리의-기본-원칙)
- [`error` 인터페이스](#error-인터페이스)
- [기본적인 에러 처리 패턴](#기본적인-에러-처리-패턴)
- [`errors` 표준 패키지 (에러 종류에 따른 처리)](#errors-표준-패키지-에러-종류에-따른-처리)
  - [`error.Is()`](#erroris)
  - [`error.As()`](#erroras)
- [Wrapper 인터페이스](#wrapper-인터페이스)
- [fmt.Errorf(), %w (에러 래핑 유틸 메서드)](#fmterrorf-w-에러-래핑-유틸-메서드)
- [패닉(Panic)과 복구(Recover)](#패닉panic과-복구recover)



## Go 에러 처리의 기본 원칙

Go에서 에러는 일반 값이다

에러는 `error` 인터페이스 타입의 값으로 다른 타입(`string`, `int`)들의 값처럼 변수에 할당하고 함수 인자로 전달하며, 함수 반환 값으로 사용할 수 있다

함수에서 문제가 발생할 가능성이 있다면 일반적으로 함수의 마지막 반환 값으로 `error` 타입을 추가하여 에러를 명시적으로 반환한다

그리고 함수를 호출하는 쪽에서는 반환된 `error` 값을 반드시 확인해야 한다

많은 언어에서 지원하는 `try-catch`, `try-except`, `try-finally` 메커니즘을 Go에서는 지원하지 않는다

Go는 `error` 인터페이스를 통한 명시적인 오류 반환(`return error`) 방식을 강력히 권장한다

정상적인 흐름의 오염과 암묵적인 오류 전파를 방지하여 읽기 쉬운 코드를 만들고 성능 오버헤드를 높이려는 목적이다


## `error` 인터페이스

`error` 인터페이스는 내장 타입이므로 명시적인 임포트없이 바로 사용할 수 있다

`error` 인터페이스 정의

```go
type error interface {
    Error() string
}
```

error 인터페이스는 `string` 값을 반환하는 `Error` 메서드를 가진다

어떤 타입이든 `Error() string` 메서드를 구현하면 `error` 타입으로 간주될 수 있다

```go
// 커스텀 에러 타입
type UserNotFound struct {
	Code int
	Message string
}

// error 인터페이스 구현
func (e *UserNotFound) Error() string {
	return fmt.Sprintf("사용자를 찾을 수 없다 (%d: %s)", e.Code, e.Message)
}
```


## 기본적인 에러 처리 패턴

```go
func add(a, b int) (result int, err error) {

	if a < 0 || b < 0 {
		return 0, errors.New("음수의 값은 더할 수 없다")
	}

	return a + b, nil
}


func main() {

	result, err := add(10, 20)

	// 함수가 에러를 반환하는지 확인한다 (에러 처리)
	if (err != nil) {
		fmt.Println("에러 발생")
		return
	}

	fmt.Println(result)

	result, err = add(-10, 20)

	// 함수가 에러를 반환하는지 확인한다 (에러 처리)
	if (err != nil) {
		fmt.Println("에러 발생")
		return
	}

	fmt.Println(result)
}
```


## `errors` 표준 패키지 (에러 종류에 따른 처리)

`errors` 표준 패키지는 에러를 편리하게 처리할 수 있는 기능을 제공한다

### `errors.New(string)`

커스텀 에러 타입을 정의하지 않고도 에러를 간편하게 만들 수 있는 유틸리티 함수이다

```go
// 에러 변수 선언
var Unauthorized = errors.New("unauthorized")
```

### `error.Is()`

`errors.Is(err, target error)` 함수는 에러 체인(`err`)을 따라가며 특정 에러 값(`target`)과 일치하는지 확인하여 특정 종류의 에러를 식별한다 (자바의 `instanceof` 느낌)

```go
// 전역 에러 변수 선언
var ErrRecordNotFound = errors.New("기록을 찾을 수 없다")

func findRecord(id int) (string, error) {
	if id == 404 {
		return "", ErrRecordNotFound
	}

	return "찾은 기록", nil
}


func main() {
	data, err := findRecord(404)

	// 에러가 ErrRecordNotFound와 같은 타입이고 값이 일치하는지 확인한다
	if errors.Is(err, ErrRecordNotFound) {
		fmt.Println("404 에러 처리")
	} else if err != nil {
		fmt.Println("다른 에러 처리")
	} else {
		fmt.Println(data)
	}
}
```

### `error.As()`

`errors.As(err error, target any)` 함수는 주어진 에러 체인(`err`) 내에서 `target`이 가리키는 특정 타입의 에러를 찾는다

만약 찾았다면 그 에러를 `target` 변수에 할당(캐스팅)하여 개발자가 에러 체인 내의 특정 에러 정보에 접근할 수 있도록 한다

```go
// 커스텀 에러 타입
type UserNotFound struct {
	Code int
	Message string
}

// error 인터페이스 구현
func (e *UserNotFound) Error() string {
	return fmt.Sprintf("사용자를 찾을 수 없다 (%d: %s)", e.Code, e.Message)
}

func findUser(id int) (string, error) {
	if id == 404 {
		return "", &UserNotFound{Code: 1001, Message: "DB 문제 발생"}
	}

	return "hansanhha", nil
}

func errors_as() {
	username, err := findUser(404)

	_ = username
	var userNotFound *UserNotFound

	if err != nil && errors.As(err, &userNotFound) {
		fmt.Println(userNotFound)
	}
}
```

## `Wrapper` 인터페이스

Go도 자바의 예외 체인(Exception Chaning)처럼 하나의 에러가 다른 에러를 포함하여 더 많은 컨텍스트를 제공할 수 있는 기능을 지원한다

Go의 `Wrapper` 인터페이스 정의

`Unwrap() error` 메서드는 현재 에러가 감싸고 있는 내부 에러(Underlying Error)를 반환한다

더 이상 감싸고 있는 에러가 없다면 `nil`을 반환한다

```go
type Wrapper interface {
    // Wrapper 인터페이스는 error 인터페이스를 임베딩한다
    // Error() string 메서드를 가질 수 있다
    error
    
    // 내부 에러를 반환하는 메서드
    Unwrap() error
}
```

[`%w`를  사용한 `fmt.Errorf()` 메서드](#fmterrorf-w-에러-래핑-유틸-메서드)는 내부적으로 `Wrapper` 인터페이스를 만족하는 에러를 생성한다

이 에러는 `Unwrap()` 메서드를 갖게 되어 원본 에러를 반환할 수 있다

더 복잡한 에러를 만들어야 할 때는 아래처럼 커스텀 에러 타입에 `Unwrap() error` 메서드를 구현하여 `Wrapper` 인터페이스를 만족시킬 수 있다

```go
var PostNotFound = errors.New("Post Not Found")

// 커스텀 에러 타입 (다른 에러를 감싸는 에러 래핑)
type EntityNotFound struct {
	Msg string
	Cause error
}

// Error() 메서드 구현: error 인터페이스 만족
func (e *EntityNotFound) Error() string {
	if e.Cause != nil {
		return fmt.Sprintf("%s: %v", e.Msg, e.Cause)
	}

	return e.Msg
}

// Unwrap() 메서드 구현: Wrapper 인터페이스 만족
func (e *EntityNotFound) Unwrap() error {
	return e.Cause
}

func findPost(id int) (string, error) {
	if id == 0 {

		// 에러 래핑(EntityNotFound)를 통해 PostNotFound를 감싼다
		return "", &EntityNotFound {
			Msg: "엔티티 이름이 비어있다",
			Cause: PostNotFound,
		}
	}

	return "post", nil
}

func custom_error_wrapper() {
	_, err := findPost(0)

	if err != nil {
		// 전체 에러 출력
		fmt.Println(err)

		// 래핑된 에러가 PostNotFound 타입이고 값이 일치하는지 확인한다
		if errors.Is(err, PostNotFound) {
			fmt.Printf("에러 발생: %v\n", PostNotFound)
		}

		// 에러가 래핑 에러인지 확인하고 래핑 에러의 정보를 추출한다
		var wrappingErr *EntityNotFound
		if errors.As(err, &wrappingErr) {
			fmt.Printf("래핑 에러 메시지: %s\n", wrappingErr.Msg)
			fmt.Printf("래핑 에러의 원본 에러: %v\n", wrappingErr.Cause)
		}
	}

}
```


## fmt.Errorf(), %w (에러 래핑 유틸 메서드)

Go 1.13 버전부터 `errors.Wrap`과 같은 외부 패키지 없이도 에러를 래핑하여 여러 체인을 만들 수 있다 -> 하나의 에러가 다른 에러에 대한 컨텍스트를 제공하도록 한다

`fmt.Errorf()`는 에러 메시지를 포함하는 `error`를 생성할 수 있는 함수로 항상 `error` 인터페이스 타입을 반환한다

`fmt.Errorf()` 함수에 `%w`를 사용하면 하나의 에러를 다른 에러에 포함시켜 에러 체인을 만들 수 있다 (에러 래핑)

에러 체인을 통해 원본 에러에 대한 컨텍스트를 추가하면서도 `errors.Is()` 나 `errors.As()`를 사용하여 체인 내의 특정 에러를 식별할 수도 있다

`%w`를 사용하지 않으면 단순히 에러 메시지를 문자열로 연결하는 것과 같아서 `errors.Is()`나 `errors.As()`가 체인을 탐색할 수 없다

```go
// 전역 에러 변수 선언
var Unauthorized = errors.New("unauthorized")

// 에러 반환
func authenticate(username string) (bool, error) {
	if username != "hansanhha" {
		return false, Unauthorized
	}

	return true, nil
}

func authorize(username string) (bool, error) {
	_, err := authenticate(username)

	// authenticate 함수에서 반환한 에러를 래핑하여 새로운 에러를 반환한다
	if err != nil {
		return false, fmt.Errorf("authorization failed: %w", err)
	}

	return true, nil
}

func main() {

	_, err := authorize("user")

	if err != nil {
		// Unauthorized를 
		fmt.Println(err)

		// 래핑된 에러가 Unauthorized와 같은 타입이고 값이 일치하는지 확인한다
		if errors.Is(err, Unauthorized) {
			fmt.Println(Unauthorized)
		}
	}
}
```


## 패닉(Panic)과 복구(Recover)

Go는 예외를 던지거나(`throws`) 잡는(`catch`) 기능을 지원하는 대신 코드 내에서 명시적으로 에러를 처리하는 방식을 선호한다

Go의 예외 처리는 `throw/catch` 메커니즘과 비슷한 `panic/recover` 메커니즘을 지원한다

`panic`은 일반적인 오류 처리(`error`)가 아닌 프로그램의 불변성이 깨져서 더이상 진행할 수 없을 때나 예외적인 상황으로 인해 전체 프로그램 종료를 유발해야 할 때 사용한다

`recover`는 `panic`에 의해 발생한 스택 언와인딩을 가로채서 `panic`의 전파를 중단시키고 `panic` 값을 반환함으로써 프로그램의 실행을 재개할 수 있게 한다 (`recover`는 오직 `defer` 함수 내에서만 유효하게 호출될 수 있다)

패닉은 런타임 패닉과 명시적 패닉으로 나뉜다
- 런타임 패틱: 논리적 오류로 인해 Go 런타임이 발생시키는 오류 (nil 포인터 역참조, 배열/슬라이스 인덱싱 범위 벗어난 접근 등)
- 명시적 패닉: 개발자가 `panic("에러 메시지")` 또는 `panic(error)`와 같이 직접 `panic` 함수를 호출하여 발생시킨 오류 (복구 불가능한 초기화 실패나 프로그램 불변성이 깨지는 심각한 상황에 사용한다)

내장 함수 `panic`을 호출하면 패닉을 생성하고 현재 고루틴의 실행을 즉시 중단시킨다 (함수에서 패닉을 반환할 수도 있다)

그리고 스택을 위로 거슬러 올라가는 스택 언와인딩(Stack Unwinding)을 하면서 `defer` 함수들을 실행시킨다 (이 때 recover 함수가 호출될 수 있다)

[지연 호출 함수](문법.md#지연-함수-지연-호출-함수)에서 내장 함수 `recover` 함수를 호출하면 현재 고루틴에서 발생한 패닉을 제거하고 일반 실행 흐름으로 되돌릴 수 있다 (panic의 전파를 멈춘다)

```go
func main() {

	defer func() {
		fmt.Println("정상 종료")
	}()

	fmt.Println("hi")

	defer func() {
		v := recover()
		fmt.Println("패닉 복구:", v)
	}()

	panic("패닉 발생")
}
```

만약 패닉에 빠진 고루틴을 복구하지 않으면 `panic`이 전파되어 전체 프로그램 자체가 충돌하게 된다

```go
func main() {

	fmt.Println("hi")

	go func() {
		panic("패닉 발생")
	}()

	time.Sleep(time.Second)
}
```
